### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by DocLM**
Hi @qoomon,
I made a Powershell version of your scripts, this allow Windows users to use your scripts without additional dependencies on their systems.

### CODE REVIEW

**Comment by qoomon** [comment]
Uh that's nice. I'll review it within the next days

**Comment by qoomon** [comment]
@DocLM It feels a little messy to put windows and unix README together. Could you just duplicate the README.md to README.windows.md and add a link to windows README in README.md

**Comment by DocLM** [comment]
Of course. @qoomon I moved Windows customization to a different README.

**Comment by qoomon** [comment]
Awesome

**Pull request merged**
